# Workflow name
name: Continuous Deployment Github

# This allows manual start of the pipeline as needed.
on: workflow_dispatch

# The list of jobs to run 
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
      
      # 2. Setup Node
      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
          
      # 3. Setup Cache
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Build Angular
      - name: Build Angular Application
        working-directory: ./tuff
        run: |
          npm install
          npm run openapi-prod
          npm run build
          
      # 5. Set Credentials
      - name: Set Credentials
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git config user.name "$GIT_USERNAME" && git config user.email "$GIT_EMAIL"
          cp ./CNAME ./tuff/dist/tuff/browser/CNAME

      # 6 Deploy
      - name: Deploy
        working-directory: ./tuff/dist/tuff/browser
        run: |
          git checkout --orphan gh-pages
          git add .
          git commit -m "gh-pages"
          git push origin HEAD:gh-pages --force